apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- target:
    kind: Service
    name: ${{ values.component_id }}
  patch: |-
    - op: replace
      path: /metadata/labels/backstage.io/kubernetes-id
      value: ${{ values.namespace }}-prod