apiVersion: backstage.io/v1alpha1
{%- if values.entityKind %}
kind: ${{ values.entityKind }}
{%- else %}
kind: Component
{%- endif %}
metadata:
  name: ${{ values.component_id }}
  {%- if values.description %}
  description: ${{ values.description }}
  {%- endif %}
  annotations:
    argocd/app-selector: app=${{ values.component_id }}
    tektonci/build-namespace: ${{ values.namespace }}-dev
    backstage.io/kubernetes-id: ${{ values.namespace }}
    backstage.io/techdocs-ref: url:https://github.com/${{ values.githubOrg }}/${{ values.repoName }}
#    backstage.io/kubernetes-namespace: ${{ values.namespace }}-dev
    backstage.io/source-location: url:https://github.com/${{ values.githubOrg }}/${{ values.repoName }}
    github.com/project-slug: ${{ values.githubOrg }}/${{ values.repoName }}
    janus-idp.io/tekton-enabled : 'true'
  links:
    - url: https://devspaces.${{ values.ocpDomain }}/dashboard/#/load-factory?url=https://github.com/${{ values.githubOrg }}/${{ values.repoName }}
      title: OpenShift Dev Spaces
      icon: web

spec:
  type: ${{ values.applicationType }}
  system: ${{ values.system }}
  lifecycle: production
  owner: ${{ values.owner }}
  {%- if values.dependsOn %}
  dependsOn:
    - ${{ values.dependsOn }}
  {%- endif %}
  {%- if values.partOf %}
  partOf:
    - ${{ values.partOf }}
  {%- endif %}
  providesApis:
    - ${{values.component_id | dump}}

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{ values.component_id }}
spec:
  type: openapi
  lifecycle: production
  owner: ${{ values.owner }}
  definition:
    $text: https://github.com/${{ values.githubOrg }}/${{ values.repoName }}/blob/main/${{ values.component_id }}/swagger
