kind: Deployment
apiVersion: apps/v1
metadata:
  name: ${{ values.component_id }}
  labels:
    app.kubernetes.io/part-of: ${{ values.component_id }}
    app.kubernetes.io/component: backstage
    backstage.io/kubernetes-id: ${{ values.namespace }}-${{ values.component_id }}
    {%- if values.quarkusS2I %}
    app.openshift.io/runtime: quarkus
    {%- endif %}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{ values.component_id }}
  template:
    metadata:
      labels:
        app: ${{ values.component_id }}
    spec:
      containers:
        - name: ${{ values.component_id }}
          image: ${{ values.imageRepository }}/${{ values.namespace }}-dev/${{ values.component_id }}:latest
          ports:
            - name: http-${{ values.port }}
              containerPort: ${{ values.port }}
              protocol: TCP
          resources:
            limits:
              memory: '300Mi'
              cpu: '300m'
