kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: ${{ values.component_id }}
  labels:
    app: ${{ values.component_id }}
    app.kubernetes.io/component: backstage
    backstage.io/kubernetes-id: ${{ values.namespace }}-${{ values.component_id }}
spec:
  to:
    kind: Service
    name: ${{ values.component_id }}
    weight: 100
  port:
    targetPort: http-${{ values.port }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None